#include <WiFiClient.h>
#include <WiFiServer.h>
#include <WiFiUdp.h>
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/69447b64-6a62-4039-beea-efc04efbbd87 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight led;
  bool push_button;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

const char* morseCode[] = {
  ".-", "-...", "-.-.", "-..", ".", "..-.", "--.", "....", "..", ".---",
  "-.-", ".-..", "--", "-.", "---", ".--.", "--.-", ".-.", "...", "-",
  "..-", "...-", ".--", "-..-", "-.--", "--.."
};

const char* nameMorse = "-.-. .... .- -- --- -.."; // Morse code for "Chamod"

const int ledPin = 2;
const int buttonPin = 12;

volatile bool buttonPressed = false;
volatile bool reset = false;

void IRAM_ATTR handleButtonPress() {
  buttonPressed = true;
  reset = true;
}

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  
  pinMode(ledPin, OUTPUT);
  pinMode(buttonPin, INPUT_PULLUP);
  
  attachInterrupt(digitalPinToInterrupt(buttonPin), handleButtonPress, FALLING);
  
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();

  if (buttonPressed) {
    buttonPressed = false;
    blinkNameInMorse();
  }
}

void blinkNameInMorse() {
  for (int i = 0; nameMorse[i] != '\0'; i++) {
    if (reset) {
      reset = false;
      i = -1; // Restart the loop
      continue;
    }

    if (nameMorse[i] == '.') {
      digitalWrite(ledPin, HIGH);
      delay(200); // Dot duration
      digitalWrite(ledPin, LOW);
    } else if (nameMorse[i] == '-') {
      digitalWrite(ledPin, HIGH);
      delay(600); // Dash duration
      digitalWrite(ledPin, LOW);
    } else {
      delay(200); // Space between parts of the same letter
    }
    delay(200); // Space between letters
  }
}




